[package]
name = "chirpycritter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.4"
midly = "0.5.2"  # TODO: Gate behind a feature